Algoritmo "Entrada e saída de dados"
// Disciplina   : [Algoritmos e Lógica I]
// Professor   : Cleitin
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Barison
// Data atual  : 08/07/2021
Var
// Seção de Declarações das variáveis 
   Nota: inteiro, Nota2: real, Nome, Nome2: caractere,
   Isactive: logico;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva("Resultados:", nota)

Fimalgoritmo